version: 2.1

workflows:
  gbl-workflow:
    jobs:
      - run-tests:
          context:
            - yul-gbl

orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  run-tests:
  #build:
    docker:
      - image: circleci/ruby:2.5.7
        auth:
          username: $DOCKERHUB_MYUSER  # can specify string literal values
          password: $DOCKERHUB_MYPASSWORD  # or project environment variable reference
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: "echo environment variables from yul-gbl context"
          command: echo $DOCKERHUB_MYUSER
      - run:
          name: "Run Rspec test"
          #command: bundle exec rspec
          command: rspec
