version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1p57
        auth:
          username: $DOCKERHUB_MYUSER  # can specify string literal values
          password: $DOCKERHUB_MYPASSWORD  # or project environment variable reference
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

